<?php
/**
 * Created by PhpStorm.
 * User: HoangND
 * Date: 2019/03/13
 * Time: 16:20
 */

namespace App\Controller;

class AjaxController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->disableAutoLayout();
    }
    public function getlstchitietloaihang(){

    }
}