<?php
/**
 * Created by PhpStorm.
 * User: HoangND
 * Date: 2019/03/13
 * Time: 16:20
 */

namespace App\Controller;

use Cake\ORM\TableRegistry;

class AjaxController extends AppController
{
    private $chitietloaihangTable;
    private $loaihangTable;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->disableAutoLayout();
        $this->chitietloaihangTable=TableRegistry::getTableLocator()->get('Chitietloaihang');
        $this->loaihangTable=TableRegistry::getTableLocator()->get('Loaihang');
    }

    public function getlstchitietloaihang()
    {
        if($this->request->is('ajax')){
            $loaiHang_id=$this->request->getData('loaihang_id');
            $tenLoaiHang=$this->loaihangTable->get($loaiHang_id)['tenloaihang'];
            $lstLoaiHang=$this->chitietloaihangTable->find('all',[
                'conditions'=>['loaihang_id'=>$loaiHang_id]
            ])->toArray();

            $this->set('tenLoaiHang',$tenLoaiHang);
            $this->set('lstLoaiHang',$lstLoaiHang);
        }
    }
}
