<?php
/**
 * Created by PhpStorm.
 * User: HoangND
 * Date: 2019/03/13
 * Time: 13:29
 */

namespace App\Controller;


use Cake\ORM\TableRegistry;

class PhoneManagerController extends LoggedController
{
    public $loaiHangTable;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
            $this->viewBuilder()->setLayout('managerLayout');
        $this->loaiHangTable=TableRegistry::getTableLocator()->get('Loaihang');

    }

    public function index(){

    }

    public function add(){
        $arrLoaiHang=[];
        $lstLoaiHang=$this->loaiHangTable->find()->toArray();
        foreach ($lstLoaiHang as $item){
            $arrLoaiHang[$item['id']]=$item['tenloaihang'];
        }
        $this->set('lstLoaiHang',$arrLoaiHang);
    }


}