<?php

/**
 * Created by PhpStorm.
 * User: HoangND
 * Date: 2019/03/13
 * Time: 13:29
 */

namespace App\Controller;

class PhoneManagerController extends LoggedController {

    private $arrLoaiHang = [];
    private $arrNhomHang = [];

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('managerLayout');
//        $this->arrLoaiHang = [['value' => 'chon', 'text' => '--Chọn hãng--', 'hidden']];
//        $lstLoaiHang = $this->Loaihang->find()->toArray();
//        $lstNhomHang = $this->Nhomhang->find()->toArray();
//        foreach ($lstLoaiHang as $item) {
//            $this->arrLoaiHang[$item['id']] = $item['tenloaihang'];
//        }
//        foreach ($lstNhomHang as $item) {
//            $this->arrNhomHang[$item['id']] = $item['tennhomhang'];
//        }
//        $this->loadComponent('validation');
//        $this->loadComponent('Csrf');
    }

    public function index() {
//        $token = $this->request->getParam('_csrfToken');
//        $this->set('csrfToken', $token);
//        $lstPhone = $this->Mathang->find()
//                ->select($this->Mathang)
//                ->select($this->Loaihang)
//                ->select($this->Chitietloaihang)
//                ->join([
//                    'Chitietloaihang' => [
//                        'table' => 'Chitietloaihang',
//                        'type' => 'INNER',
//                        'conditions' => 'Chitietloaihang.id=Mathang.chitietloaihang_id'
//                    ], 'Loaihang' => [
//                        'table' => 'Loaihang',
//                        'type' => 'INNER',
//                        'conditions' => 'Loaihang.id=Chitietloaihang.loaihang_id'
//                    ]
//                ])
//                ->toArray();
//
//        $this->set('lstPhone', $lstPhone);
    }

    public function add() {
        $this->set('lstLoaiHang', $this->arrLoaiHang);
        $this->set('lstNhomHang', $this->arrNhomHang);
        if ($this->request->isPost()) {
            $reqMatHang = $this->request->getData();
            $validation = $this->Mathang->newEntity($reqMatHang, ['validate' => 'Update']);
            $validationError = $validation->errors();
            if (!empty($validationError)) {
                $this->Flash->error($this->validation->getmessage($validationError));
            } else {
                $newMatHang = $this->Mathang->newEntity();
                move_uploaded_file($reqMatHang['hinhanh']['tmp_name'], 'img/phone/' . $reqMatHang['hinhanh']['name']);
                $newMatHang->tenmathang = $reqMatHang['tenmathang'];
                $newMatHang->soluong = $reqMatHang['soluong'];
                $newMatHang->giaban = $reqMatHang['giaban'];
                $newMatHang->hinhanh = $reqMatHang['hinhanh']['name'];
                $newMatHang->hienthi = $reqMatHang['hienthi'];
                $newMatHang->chitietloaihang_id = $reqMatHang['chitietloaihang'];
                $newMatHang->nhomhang_id = $reqMatHang['nhomhang'];
                if ($this->Mathang->save($newMatHang)) {
                    $this->redirect('/manager/phone_manager');
                }
            }
        }
    }

    public function edit($id = "") {
        $this->set('lstLoaiHang', $this->arrLoaiHang);
        $this->set('lstNhomHang', $this->arrNhomHang);

        if ($id != "") {
            $mathang = $this->Mathang->get($id);
            $chitietloaihang = $this->Chitietloaihang->get($mathang['chitietloaihang_id']);
            $loaihang = $this->Loaihang->get($chitietloaihang['loaihang_id']);
            $getlstChiTiet = $this->Chitietloaihang->find('all', [
                        'conditions' => ['loaihang_id' => $loaihang['id']]
                    ])->toArray();
            $arrChitietloaihang = [['value' => 'chon', 'text' => '--Chọn loại hàng--', 'hidden']];
            foreach ($getlstChiTiet as $item) {
                $arrChitietloaihang[$item['id']] = $item['tenchitietloaihang'];
            }
            $this->set('mathang', $mathang);
            $this->set('loaihangid', $loaihang['id']);
            $this->set('lstChitietloaihang', $arrChitietloaihang);
        } else {
            $this->redirect('/manager/phone_manager');
        }


        if ($this->request->isPost()) {
            $reqMatHang = $this->request->getData();
            $hinhanh = $reqMatHang['anhcu'];
            if ($reqMatHang['hinhanhmoi']['error'] == 0) {
                $hinhanh = $reqMatHang['hinhanhmoi']['name'];
                move_uploaded_file($reqMatHang['hinhanhmoi']['tmp_name'], 'img/phone/' . $hinhanh);
            }
            $newMatHang = $this->Mathang->get($id);
            $newMatHang->tenmathang = $reqMatHang['tenmathang'];
            $newMatHang->soluong = $reqMatHang['soluong'];
            $newMatHang->giaban = $reqMatHang['giaban'];
            $newMatHang->hinhanh = $hinhanh;
            $newMatHang->hienthi = $reqMatHang['hienthi'];
            $newMatHang->chitietloaihang_id = $reqMatHang['chitietloaihang'];
            $newMatHang->nhomhang_id = $reqMatHang['nhomhang'];
            if ($this->Mathang->save($newMatHang)) {
                $this->redirect('/manager/phone_manager');
            }
        }
    }

}
