<?php
/**
 * Created by PhpStorm.
 * User: HoangND
 * Date: 2019/03/13
 * Time: 13:29
 */

namespace App\Controller;


class PhoneManagerController extends LoggedController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('managerLayout');

    }

    public function index()
    {
        $lstHienThi=$this->Mathang->find('all')
            ->select($this->Mathang)
            ->select($this->Chitietloaihang)
            ->select($this->Loaihang)
            ->join([
                'Chitietloaihang'=>[
                    'table'=>'chitietloaihang',
                    'type'=>'INNER',
                    'conditions'=>'Chitietloaihang.id = mathang.chitietloaihang_id'
                ],'Loaihang'=>[
                    'table'=>'loaihang',
                    'type'=>'INNER',
                    'conditions'=>'Loaihang.id=Chitietloaihang.loaihang_id'
                ],

            ])->toArray();
        echo '<pre>';
        var_dump($lstHienThi[0]['Chitietloaihang']['id']);
    }

    public function edit(){

    }

    public function delete(){
        $this->autoRender=false;

    }

    public function add()
    {
        $arrLoaiHang = [['value' => 'chon', 'text' => '--Chọn hãng--', 'hidden']];
        $arrNhomHang = [];
        $lstLoaiHang = $this->loaiHangTable->find()->toArray();
        $lstNhomHang = $this->nhomHangTable->find()->toArray();
        foreach ($lstLoaiHang as $item) {
            $arrLoaiHang[$item['id']] = $item['tenloaihang'];
        }
        foreach ($lstNhomHang as $item) {
            $arrNhomHang[$item['id']] = $item['tennhomhang'];
        }
        $this->set('lstLoaiHang', $arrLoaiHang);
        $this->set('lstNhomHang', $arrNhomHang);


        if ($this->request->isPost()) {
            $reqUser = $this->request->getData();
            if ($reqUser['hinhanh']['error'] === 0) {
                if (isset($reqUser['chitietloaihang'])) {
                    move_uploaded_file($reqUser['hinhanh']['tmp_name'], 'img/phone/' . $reqUser['hinhanh']['name']);
                    $newUser = $this->matHangTable->newEntity();
                    $newUser->tenmathang = $reqUser['tenmathang'];
                    $newUser->soluong = $reqUser['soluong'];
                    $newUser->giaban = $reqUser['giaban'];
                    $newUser->hinhanh = $reqUser['hinhanh']['name'];
                    $newUser->hienthi = $reqUser['hienthi'];
                    $newUser->chitietloaihang_id = $reqUser['chitietloaihang'];
                    $newUser->nhomhang_id = $reqUser['nhomhang'];
//                    echo '<pre>';
//                    var_dump($newUser);die();
                    $this->matHangTable->save($newUser);
                }
            }
        }
    }
}


